name = "Flywheel Gregcraft"
author = "CreepSean"
version = "0.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f2913cbd35183fd3c7b6ab14cfe9115a161a51b20ddbdf5b97267040bef2f65"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
