name = "Flywheel Gregcraft"
author = "CreepSean"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62b99f50ab83c143fd6248d98868d584b2d30501e1ea8c33f41003eb2a9dae92"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
