name = "Flywheel Gregcraft"
author = "CreepSean"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70a0dba1633a86bc80240e1a11deab6d54f740ed3b6770de36104a3cdb29e78d"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
