name = "Flywheel Gregcraft"
author = "CreepSean"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3742a5367df61956ab9c6233a15b3f880b74976ed74c5dd466e49f9a51683e12"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
